-- MySQL Script generated by MySQL Workbench
-- Mon Feb 20 15:38:59 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bio` DEFAULT CHARACTER SET utf8 ;
USE `bio` ;

-- -----------------------------------------------------
-- Table `bio`.`file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bio`.`file` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `path` VARCHAR(127) NOT NULL,
  `name` VARCHAR(113) NOT NULL,
  `create_at` DATETIME NOT NULL,
  `update_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bio`.`data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bio`.`data` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `time` VARCHAR(71) NOT NULL,
  `number` INT UNSIGNED NOT NULL,
  `name` VARCHAR(127) NOT NULL,
  `event` VARCHAR(71) NOT NULL,
  `status` BINARY NOT NULL DEFAULT false,
  `create_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bio`.`person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bio`.`person` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(97) NOT NULL,
  `ci` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bio`.`date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bio`.`date` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `seconds` TINYINT UNSIGNED NOT NULL,
  `minutes` TINYINT UNSIGNED NOT NULL,
  `hours` TINYINT UNSIGNED NOT NULL,
  `number_day` TINYINT UNSIGNED NOT NULL,
  `number_weeks_day` TINYINT UNSIGNED NOT NULL,
  `number_month` TINYINT UNSIGNED NOT NULL,
  `year` SMALLINT UNSIGNED NOT NULL,
  `number_years_day` SMALLINT UNSIGNED NOT NULL,
  `weekday` VARCHAR(17) NOT NULL,
  `month` VARCHAR(17) NOT NULL,
  `unix_time` INT UNSIGNED NOT NULL,
  `event` VARCHAR(71) NOT NULL,
  `persona_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fecha_persona_idx` (`persona_id` ASC),
  CONSTRAINT `fk_fecha_persona`
    FOREIGN KEY (`persona_id`)
    REFERENCES `bio`.`person` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
